### ISSUE TITLE
VAE重建初始几帧有虚影问题

### ISSUE THREAD

**Issue by Sylvain-ssy** [THUDM/CogVideo#102]
### System Info / 系統信息

diffusers 0.30.0

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

使用的是inference/cli_vae_demo.py脚本，输入的原视频在初始几帧如果人物和画面有较快较大幅度的运动，重建出来的画面会有虚影的情况，但是之后的帧（即使有大幅度运动）画面都是正常的。输入的帧序列大小为40 x 960 x 720

### Expected behavior / 期待表现

想确认下是否是普遍问题，是的话有没有优化方法

**Comment by zRzRzRzRzRzRzR** [comment]
能尝试分享一个视频吗，这个视频是6秒，每秒8帧 720 x 480的吧

**Comment by Sylvain-ssy** [comment]
原视频fps是24，960 x 720的大小，第一个case是输入原视频的前40帧不做resize，所以视频长度是1.67秒。

第二个case是按照推荐的方法，fps为8，size是720 x 480，仍然会有相同的情况出现

https://github.com/user-attachments/assets/e6555e87-e825-4b57-92bb-97942e053814


https://github.com/user-attachments/assets/e77339cd-20e7-4189-bbe3-ab20c427d7f9

**Comment by bendanzzc** [comment]
+1，我也遇到过，一帧一帧对比过，前8帧和原视频会有肉眼可见的diff，后面就好了，肉眼几乎看不出来差别

**Comment by tengjiayan20** [comment]
VAE reconstruction does not need to limit the resolution and duration of the video, but it needs to ensure that the number of input frames is 4K+1. This is related to the structure of our VAE, which extracts the first frame for separate processing and then compresses the subsequent 4K frames by 4 times, in order to process both video and images at the same time.

VAE的重建不需要限制视频的分辨率和时长，但是需要确保输入的帧数是4K+1，这和我们vae的结构有关，它是将第一帧提出来单独处理，然后之后的4K帧压缩4倍，目的是可以同时处理视频和图像。

**Comment by bendanzzc** [comment]
确实，改成4K+1 没问题了

**Comment by tengjiayan20** [comment]
> 确实，改成4K+1 没问题了
> 
> 另外请教下，针对这个特性的话，以下假设是否成立呢：比如我输入的frames=49，encoder之后的latents的shape是 B C 13 H W，其中 latents[:,:,0:1,...]只是第一帧的feature，和latents[:,:,1:,...]是后面48帧的latents，两者互相独立，可以分别单独decoder且不影响效果 @tengjiayan20

Because it is a causal conv, each frame only pays attention to the frame before it, so latents[:,:,0:t,...] can be decoded alone without any effect, but latents[:,:,t:,...] cannot be decoded alone, because it needs the information of the previous frame when encoding.

由于是causal conv，每一帧只会关注它之前的帧，所以latents[:,:,0:t,...]可以单独decode无影响，但latents[:,:,t:,...]不能单独decode，因为它在encode的时候是需要前面的帧的信息的

**Comment by bendanzzc** [comment]
@tengjiayan20 还想请教个问题，因为训练时候49帧encode出来的latents的T=13，但实际inference的时候 latents的维度T=12，训练推理对不齐会导致模型性能有偏差嘛，或者训练的时候取 T=0:12的lantents进行训练。谢谢

**Comment by tengjiayan20** [comment]
> @tengjiayan20 还想请教个问题，因为训练时候49帧encode出来的latents的T=13，但实际inference的时候 latents的维度T=12，训练推理对不齐会导致模型性能有偏差嘛，或者训练的时候取 T=0:12的lantents进行训练。谢谢

实际推理的时候latents的维度也是T=13呀

**Comment by bendanzzc** [comment]
> > 确实，改成4K+1 没问题了
> > 另外请教下，针对这个特性的话，以下假设是否成立呢：比如我输入的frames=49，encoder之后的latents的shape是 B C 13 H W，其中 latents[:,:,0:1,...]只是第一帧的feature，和latents[:,:,1:,...]是后面48帧的latents，两者互相独立，可以分别单独decoder且不影响效果 @tengjiayan20
> 
> Because it is a causal conv, each frame only pays attention to the frame before it, so latents[:,:,0:t,...] can be decoded alone without any effect, but latents[:,:,t:,...] cannot be decoded alone, because it needs the information of the previous frame when encoding.
> 
> 由于是causal conv，每一帧只会关注它之前的帧，所以latents[:,:,0:t,...]可以单独decode无影响，但latents[:,:,t:,...]不能单独decode，因为它在encode的时候是需要前面的帧的信息的

@tengjiayan20 您好，不好意思再次打扰，通过这个回复可以看到 latents不能从[;,;,t:...]进行decode，但是看代码里 decode是
` current_frames = self.vae.decode(latents[:, :, start_frame:end_frame]).sample`
看起来是可以从 latents里中间diecode的，这个有什么原理嘛，另外我看 不同的T decode的frames也不是等比增加的，再latents里的T=1,2,3时，decode出来的frames的T=1,8,9,

期盼您的解答，谢谢

**Comment by bendanzzc** [comment]
> 1,2,3对应decode出来应该是1，5，9，k+1 -> 4k+1，你说的代码里的操作应该是在串行地在时间维度上对latent进行切分操作，为了减少显存

谢谢，一针见血，醍醐灌顶
