### ISSUE TITLE
训练视频过多会直接结束进程

### ISSUE THREAD

**Issue by peki12345** [THUDM/CogVideo#146]
### System Info / 系統信息

遵循官方安装流程

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

非常好的工作！我使用200个视频进行全参数finetune，训练正常，模型表现也正常。然而，当我将视频扩展为2000个后，在训练开始前（显示loss前）进程就会直接结束，没有任何报错信息，我想知道这是为什么？

### Expected behavior / 期待表现

感谢回复

**Comment by spacegoing** [comment]
That's because their dataloader loads all data all at once into memory, without dist sharding even with DDP and Distributed Sampler enabled, which leads to OOM error.

Have to implements a customized dataloader for training on large datasets

**Comment by bertjiazheng** [comment]
I have implemented it to make it load video and caption online. You can check the implementation [here](https://github.com/bertjiazheng/CogVideo/blob/dev/sat/data_video.py#L359-L453). 

In addition, I load the 'video_path' and 'caption' from a CSV file instead of parsing the video and caption from the given path.

**Comment by zRzRzRzRzRzRzR** [comment]
Awesome, we will review it as soon as possible. Additionally, we suggest you provide a PR instead of a teahouse. CSV is a better way. We also hope to standardize the format of the fine-tuning dataset. For now, the best way is to follow the dataset format we provided to Ding.

We will soon try testing on PEFT / diffusers, and we believe this part of the work will be supported.

**Comment by bertjiazheng** [comment]
Sure, I will create a PR to load videos and captions online. I'll keep the dataset structure the same since it has changed significantly.

**Comment by peki12345** [comment]
> Sure, I will create a PR to load videos and captions online. I'll keep the dataset structure the same since it has changed significantly.

非常感谢您的实现，我如果使用您的新PR，需要把数据格式变成CSV吗？还是继续保持原始的mp4和txt呢？

**Comment by bertjiazheng** [comment]
As suggested by @zRzRzRzRzRzRzR, PR https://github.com/THUDM/CogVideo/pull/181 follows the original dataset format. 

If you prefer to use CSV, you can take a look at the branch here https://github.com/bertjiazheng/CogVideo/tree/dev

**Comment by zRzRzRzRzRzRzR** [comment]
sure, in Aug 29 I will check it
