### ISSUE TITLE
What code was used for evaluating Fréchet Video Distance(FVD)?

### ISSUE THREAD

**Issue by Maxlinn** [THUDM/CogVideo#25]
Hi hong and the whole THUDM team, thanks for your hard work and CogVideo seems really interesting!

In the "5.1 Machine Evaluation" section of your paper, you mentioned Inception Score(IS)  was calculated using the official code of TGAN-v2, that's nice and handy.
But i can't find out how Fréchet Video Distance(FVD) was evaluated. More specifically, which library or code did you choose for evaluating FVD? I carefully looked into your paper and codebase but didn't find some clue.

Did i miss something? Or could you please give me some hint? Thanks in advance!

**Comment by wenyihong** [comment]
Thanks for pointing this out! We use the official code of TATS to evaluate FVD, and we will add this to our lastest version of the paper. Also in a previous version of this paper, we had a bug in the FVD evaluation of both UCF-101 and Kinetics-600
due to using a wrong I3D checkpoint, and will correct the results in this version.

**Comment by Maxlinn** [comment]
thanks for your kind reply, that's very helpful!
