### ISSUE TITLE
A segment fault was encountered during inference

### ISSUE THREAD

**Issue by xiefan233** [THUDM/CogVideo#33]
![image](https://user-images.githubusercontent.com/44406605/221466006-5826429b-2612-44df-811f-daa61cb83819.png)
Can you tell me how to solve it?
Thanks.

**Comment by xiefan233** [comment]
The problem is with import icetk. Just reinstall icetk.

**Comment by boyu-chen-intern** [comment]
Hi! Dears, I'm having this issue as well, and I've reinstalled icetk and it still doesn't fix the issue. I noticed that when executing the script, my CPU memory usage has been rising, and finally ran full 15.9/15.9GB, and the space occupation has also temporarily increased by more than a dozen G, may I ask how much CPU memory and space requirements are needed to run the model, is the problem of the segfault fault I encountered above because of this? Thank you!
