### ISSUE TITLE
dynamic_cfg seems wrong in diffusers' impl

### ISSUE THREAD

**Issue by eugenelyj** [THUDM/CogVideo#337]
Suppose you want to implement increasing or decreasing cfg, in [this line](https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/cogvideo/pipeline_cogvideox_image2video.py#L778), the t.item() should be replaced with i or (num_inference_steps-i)

**Comment by yiyixuxu** [comment]
I think it is same as the original impl 
the DynamicCFG guider is called here https://github.com/THUDM/CogVideo/blob/628f7366280da57af84c6e1ee60fa180a16c61f1/sat/sgm/modules/diffusionmodules/sampling.py#L518

and the algorithem is here 
https://github.com/THUDM/CogVideo/blame/628f7366280da57af84c6e1ee60fa180a16c61f1/sat/sgm/modules/diffusionmodules/guiders.py#L60


could be wrong though - I will let @zRzRzRzRzRzRzR to verify if it's the case -

**Comment by zRzRzRzRzRzRzR** [comment]
If directly use t.item(), it may result in a mismatch between the calculation of the guidance coefficient and the actual iteration steps due to the nonlinearity of time steps or differences in scheduler implementations.

By replacing t.item() with i or num_inference_steps - i, we ensure that the dynamic adjustment of the guidance coefficient accurately corresponds to the iteration steps.

In conclusion, I believe this modification should be correct.

**Comment by tengjiayan20** [comment]
issue https://github.com/THUDM/CogVideo/issues/267 has explained this question.
