### ISSUE TITLE
Does sat finetune support to resume the lastest checkpoint to continue training

### ISSUE THREAD

**Issue by trouble-maker007** [THUDM/CogVideo#372]
I found that if the training processing break, it can not resume the lastest checkpoint to continue training

**Comment by zRzRzRzRzRzRzR** [comment]
yes, do you using sat or diffusers, for diffusers， just add `resume_from_checkpoint`

**Comment by trouble-maker007** [comment]
@zRzRzRzRzRzRzR I use sat, how to add the resume_from_checkpoint?

**Comment by zRzRzRzRzRzRzR** [comment]
SAT indeed does not provide a direct solution, but there is a way
You directly change the address of the trained model to the training address, and modify the name of that folder to 1, and also change the number in latest to 1
In this way, the SAT system mistakenly thinks that this is a model that has just started training and can continue training.
(This is indeed because the framework is not well adapted)

**Comment by trouble-maker007** [comment]
@zRzRzRzRzRzRzR thanks for quickly response, looking forward to the diffusers version

**Comment by zRzRzRzRzRzRzR** [comment]
Now you can using wirh https://github.com/a-r-r-o-w/cogvideox-factory
