### ISSUE TITLE
[Q] Is it possible to generate portrait videos i.e 480x720 instead of 720x480p out of the box

### ISSUE THREAD

**Issue by INF800** [THUDM/CogVideo#45]
If no, how to do it?

**Comment by zRzRzRzRzRzRzR** [comment]
Unfortunately, the resolution is ONLY 720 x 480. 😔

**Comment by onepeachbiubiubiu** [comment]
> Sorry, it’s not possible at the moment, but similar effects can be achieved through other methods such as SR and frame interpolation using some engineering implementations.

Hi, I would like to know why this is not possible, is it because the code for other finetune resolutions is not ready right now, or for some reason it is simply not possible to implement other finetune resolutions. I was able to infer 384x512 directly with the diffusers version of 5b, although I deduced that there was noise on the left and right sides. Can I directly use 384x512 video to finetune?
