### ISSUE TITLE
Update colab for the new image to video model?

### ISSUE THREAD

**Issue by sdes21** [THUDM/CogVideo#508]
### Feature request  / 功能建议

Hey would it be possible to modify the colab to run the new model for i2v? I tried changing the code to use the new model instead but there were errors. 

### Motivation / 动机

Just to ensure the colab works again. 

### Your contribution / 您的贡献

I tried updating the code but threw errors

**Comment by zRzRzRzRzRzRzR** [comment]
https://github.com/huggingface/diffusers/pull/9877

https://github.com/zRzRzRzRzRzRzR/diffusers/tree/cogvideox1.1-5b
Try installing diffusers from here, as the pull request has not been merged yet.
We did not update to Colab 1.5 because the usage method of 1.5 is similar to 1.0; you can refer to our updated cli_demo and make modifications yourself.

**Comment by sdes21** [comment]
Worked but went OOM before generating the final output. Closing this issue as the colab worked.
