### ISSUE TITLE
cogvideox微调的代码选择

### ISSUE THREAD

**Issue by AmazDeng** [THUDM/CogVideo#618]
@zRzRzRzRzRzRzR  @wenyihong @OleehyO @huangshiyu13 @bertjiazheng 

开发者您好，感谢cogvideo的开源工作。有2个问题微调方面的问题想请教一下：

1.CogVideoX-5B，CogVideoX-5B-I2V，这2个项目项目可以用cogvideox-factory项目微调吗（代码地址：https://github.com/a-r-r-o-w/finetrainers）？
2.CogVideoX-5B，CogVideoX-5B-I2V，CogVideoX1.5-5B，CogVideoX1.5-5B-I2V，这四个项目，可以用SAT代码微调吗（代码地址：https://github.com/THUDM/CogVideo/tree/main/sat）？

也就是说：
1.CogVideoX-5B，CogVideoX-5B-I2V同时支持cogvideox-factory代码和SAT代码的微调吗？
2.CogVideoX1.5-5B，CogVideoX1.5-5B-I2V只支持SAT代码的微调吗？

另外，开发者建议是使用SAT代码微调还是使用cogvideox-factory代码微调？

**Comment by AmazDeng** [comment]
@wenyihong @OleehyO @huangshiyu13 @bertjiazheng 

1.sat可以用来多卡训练，需要高配版显卡，显存高，卡多，可以全量从零开始训练。目前只支持CogVideoX-5B和CogVideoX-5B-I2V
2.diffusers可以支持单卡微调，需要的显存低，支持低端显卡。目前支持CogVideoX-5B，CogVideoX-5B-I2V，CogVideoX1.5-5B，CogVideoX1.5-5B-I2V

我这样理解，对吗？

**Comment by zRzRzRzRzRzRzR** [comment]
1. sat部分现在代码没有进行维护，在之后的新模型以及框架，sat方案会完全弃用。
2.diffusers方案会逐渐实现多卡训练，支持目前的所有模型，我们会有人员维护。

**Comment by DidiD1** [comment]
> 1. sat部分现在代码没有进行维护，在之后的新模型以及框架，sat方案会完全弃用。
>    2.diffusers方案会逐渐实现多卡训练，支持目前的所有模型，我们会有人员维护。

请问现在可以用diffusers的代码和脚本训练V1.5的lora吗，没有看到有官方的说明。谢谢。

**Comment by Passenger12138** [comment]
🚀 **We are excited to release the LoRA fine-tuning code for CogVideoX 1.5 by Diffusers**, designed specifically for image-to-video (image2video) tasks! This update brings significant improvements and new features to elevate your training experience. The full training startup code can be found in the `finetune` folder. Here's what's new:

### 🔥 Key Features & Improvements:
1. **💥 Bucket-based Multi-Resolution Training**: Unlock unparalleled model adaptability and performance across videos of all resolutions. This groundbreaking feature boosts the model’s ability to handle diverse video qualities with ease!
   
2. **⚡ Fixed RoPE (Relative Position Encoding) Configuration Error**: We’ve optimized the position encoding mechanism, solving the error in the original CogVideo code, resulting in smoother training and higher-quality outputs. No more misconfigurations—just pure efficiency!

3. **🔧 Corrected OFS Embedding Issue**: Previously, OFS embedding was incorrectly set to None in the original code. Now, it’s properly configured for stability and precision, improving the overall reliability and robustness of the model.

### ✅ Summary of Fixes:
- **Multi-resolution Support** 🖼️
- **Accurate Positional Encoding** 📍
- **Correct OFS Embedding Setup** 🔑
- **Optimized Multi-GPU Fine-Tuning** 💻

With these changes, you can now start training with **just one command**—simple, fast, and effective! 

🔗 **Dive into the code** and elevate your projects:  
[https://github.com/Passenger12138/CogVideoX-5B-I2V-v1.5-lora-train/tree/main/finetune](https://github.com/Passenger12138/CogVideoX-5B-I2V-v1.5-lora-train/tree/main/finetune)


🚀 **我们激动地宣布发布了基于 Diffusers 的 LoRA 微调代码，用于 CogVideoX 1.5，并支持图像到视频（image2video）任务！** 本次更新带来了重大的改进和新特性，训练启动代码可以在 `finetune` 文件夹中找到。以下是主要的新功能：

### 🔥 **关键功能与改进：**
1. **💥 基于桶的多分辨率训练**：释放前所未有的模型适应性和性能，适用于各种分辨率的视频。此项突破性功能增强了模型对不同视频质量的处理能力！
   
2. **⚡ 修复了 RoPE（相对位置编码）配置错误**：我们优化了位置编码机制，解决了原始 CogVideo 代码中的错误，从而提高了训练效率和输出质量。不再有配置错误——只剩下高效训练！

3. **🔧 解决了 OFS 嵌入设置为 None 的问题**：原始代码中，OFS 嵌入错误地设置为 None。现在它已经正确配置，提升了模型的稳定性和可靠性，确保了模型的精准性。

### ✅ **修复汇总：**
- **多分辨率支持** 🖼️
- **准确的位置编码** 📍
- **正确的 OFS 嵌入设置** 🔑
- **优化的多卡微调** 💻

通过这些改进，您现在只需**一条命令**就能开始训练——简单、快速、有效！

🔗 **立即体验我们的代码**，提升您的项目：  
[https://github.com/Passenger12138/CogVideoX-5B-I2V-v1.5-lora-train/tree/main/finetune](https://github.com/Passenger12138/CogVideoX-5B-I2V-v1.5-lora-train/tree/main/finetune)




### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

🔗 **Dive into the code** and elevate your projects:  
[https://github.com/Passenger12138/CogVideoX-5B-I2V-v1.5-lora-train/tree/main/finetune](https://github.com/Passenger12138/CogVideoX-5B-I2V-v1.5-lora-train/tree/main/finetune)

### Expected behavior / 期待表现

🔗 **Dive into the code** and elevate your projects:  
[https://github.com/Passenger12138/CogVideoX-5B-I2V-v1.5-lora-train/tree/main/finetune](https://github.com/Passenger12138/CogVideoX-5B-I2V-v1.5-lora-train/tree/main/finetune)
